import file3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.col00 = QtWidgets.QTextBrowser(self.centralwidget)
        self.col00.setGeometry(QtCore.QRect(170, 60, 71, 61))
        self.col00.setStyleSheet("background-color: rgb(170, 85, 255);")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(50)
        self.col00.setFont(font)
        self.col00.setObjectName("col00")
        self.col01 = QtWidgets.QTextBrowser(self.centralwidget)
        self.col01.setGeometry(QtCore.QRect(240, 60, 71, 61))
        self.col01.setStyleSheet("background-color:rgb(170, 85, 255);")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(50)
        self.col01.setFont(font)
        self.col01.setObjectName("col01")
        self.col02 = QtWidgets.QTextBrowser(self.centralwidget)
        self.col02.setGeometry(QtCore.QRect(310, 60, 71, 61))
        self.col02.setStyleSheet("background-color:rgb(170, 85, 255);")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(50)
        self.col02.setFont(font)
        self.col02.setObjectName("col02")
        self.col10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.col10.setGeometry(QtCore.QRect(170, 120, 71, 61))
        self.col10.setStyleSheet("background-color:rgb(170, 85, 255);")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(50)
        self.col10.setFont(font)
        self.col10.setObjectName("col10")
        self.col11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.col11.setGeometry(QtCore.QRect(240, 120, 71, 61))
        self.col11.setStyleSheet("background-color:rgb(170, 85, 255);")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(50)
        self.col11.setFont(font)
        self.col11.setObjectName("col11")
        self.col20 = QtWidgets.QTextBrowser(self.centralwidget)
        self.col20.setGeometry(QtCore.QRect(170, 180, 71, 61))
        self.col20.setStyleSheet("background-color:rgb(170, 85, 255);")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(50)
        self.col20.setFont(font)
        self.col20.setObjectName("col20")
        self.col21 = QtWidgets.QTextBrowser(self.centralwidget)
        self.col21.setGeometry(QtCore.QRect(240, 180, 71, 61))
        self.col21.setStyleSheet("background-color:rgb(170, 85, 255);")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(50)
        self.col21.setFont(font)
        self.col21.setObjectName("col21")
        self.col12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.col12.setGeometry(QtCore.QRect(310, 120, 71, 61))
        self.col12.setStyleSheet("background-color:rgb(170, 85, 255);")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(50)
        self.col12.setFont(font)
        self.col12.setObjectName("col12")
        self.col22 = QtWidgets.QTextBrowser(self.centralwidget)
        self.col22.setGeometry(QtCore.QRect(310, 180, 71, 61))
        self.col22.setStyleSheet("background-color:rgb(170, 85, 255);")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(50)
        self.col22.setFont(font)
        self.col22.setObjectName("col22")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(160, 260, 93, 28))
        self.btn2.setObjectName("btn2")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(290, 260, 93, 28))
        self.btn1.setObjectName("btn1")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(160, 310, 91, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(270, 310, 91, 41))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(380, 310, 101, 41))
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(500, 310, 91, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 370, 111, 41))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 430, 104, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.DFSG = QtWidgets.QTextEdit(self.centralwidget)
        self.DFSG.setGeometry(QtCore.QRect(160, 360, 91, 51))
        self.DFSG.setObjectName("DFSG")
        self.DFSC = QtWidgets.QTextEdit(self.centralwidget)
        self.DFSC.setGeometry(QtCore.QRect(160, 430, 91, 51))
        self.DFSC.setObjectName("DFSC")
        self.BFSG = QtWidgets.QTextEdit(self.centralwidget)
        self.BFSG.setGeometry(QtCore.QRect(270, 360, 91, 51))
        self.BFSG.setObjectName("BFSG")
        self.BFSC = QtWidgets.QTextEdit(self.centralwidget)
        self.BFSC.setGeometry(QtCore.QRect(270, 430, 91, 51))
        self.BFSC.setObjectName("BFSC")
        self.AG = QtWidgets.QTextEdit(self.centralwidget)
        self.AG.setGeometry(QtCore.QRect(380, 360, 101, 51))
        self.AG.setObjectName("AG")
        self.AC = QtWidgets.QTextEdit(self.centralwidget)
        self.AC.setGeometry(QtCore.QRect(380, 430, 104, 51))
        self.AC.setObjectName("AC")
        self.DFSLG = QtWidgets.QTextEdit(self.centralwidget)
        self.DFSLG.setGeometry(QtCore.QRect(500, 360, 91, 51))
        self.DFSLG.setObjectName("DFSLG")
        self.DFSLC = QtWidgets.QTextEdit(self.centralwidget)
        self.DFSLC.setGeometry(QtCore.QRect(500, 430, 91, 51))
        self.DFSLC.setObjectName("DFSLC")
        self.limit = QtWidgets.QSpinBox(self.centralwidget)
        self.limit.setGeometry(QtCore.QRect(490, 150, 91, 22))
        self.limit.setObjectName("limit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(490, 110, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        c00,c01,c02,c10,c11,c12,c20,c21,c22=(1,2,3,8,6,"",7,5,4)
        self.col00.setText(str(c00))
        self.col01.setText(str(c01))
        self.col02.setText(str(c02))
        self.col10.setText(str(c10))
        self.col11.setText(str(c11))
        self.col12.setText(str(c12))
        self.col20.setText(str(c20))
        self.col21.setText(str(c21))
        self.col22.setText(str(c22))
        DFS=file3.recherchDFS(file3.s0,file3.goal)
        
        BFS=file3.recherchBFS(file3.s0, file3.goal)
        A=file3.aetoile(file3.s0, file3.goal)

        self.DFSC.setText(str(len(DFS[0])-1))
        self.DFSG.setText(str(DFS[2]-1))
        self.BFSC.setText(str(len(BFS[0])-1))
        self.BFSG.setText(str(BFS[2]-1))
        self.AC.setText(str(len(A[0])-1))
        self.AG.setText(str(A[2]-1))

        self.btn2.clicked.connect(self.Algofind)
        
    def afiche(self,lis,pos):
        if(pos<len(lis[0])):
                if(str(lis[0][pos][0][0])!="-1"):
                        self.col00.setText(str(lis[0][pos][0][0]))
                else:
                       self.col00.setText("")

                if(str(lis[0][pos][0][1])!="-1"):
                        self.col01.setText(str(lis[0][pos][0][1]))
                else:
                       self.col01.setText("")
                if(str(lis[0][pos][0][2])!="-1"):
                        self.col02.setText(str(lis[0][pos][0][2]))
                else:
                       self.col02.setText("")
                if(str(lis[0][pos][1][0])!="-1"):
                        self.col10.setText(str(lis[0][pos][1][0]))
                else:
                       self.col10.setText("")

                if(str(lis[0][pos][1][1])!="-1"):
                
                        self.col11.setText(str(lis[0][pos][1][1]))
                else:
                       self.col11.setText("")

                if(str(lis[0][pos][1][2])!="-1"):
                        self.col12.setText(str(lis[0][pos][1][2]))
                else:
                       self.col12.setText("")
                if(str(lis[0][pos][2][0])!="-1"):
                        self.col20.setText(str(lis[0][pos][2][0]))
                else:
                       self.col20.setText("")
                if(str(lis[0][pos][2][1])!="-1"):
                        self.col21.setText(str(lis[0][pos][2][1]))
                else:
                       self.col21.setText("")
                if(str(lis[0][pos][2][2])!="-1"):
                        self.col22.setText(str(lis[0][pos][2][2]))
                else:
                       self.col22.setText("")
                pos+=1
                print(pos)
                self.btn1.clicked.connect(lambda:self.afiche(lis,pos))
        return None


    
    
    def Algofind(self):
        self.clearr()
        pos=0
        name=self.comboBox.currentText()
        match name:
                case "DFS":
                        listgere=[]
                        listgere=file3.recherchDFS(file3.s0,file3.goal)
                        self.btn1.setEnabled(True)
                        self.btn1.clicked.connect(lambda:self.afiche(listgere,pos))
                        return None
                        
                case "DFSL":
                        listgere=[]
                        listgere=file3.recherchDFSL(file3.s0, file3.goal,int(self.limit.text()))
                        self.btn1.setEnabled(True)
                        self.DFSLC.setText(str(len(listgere[0])-1))
                        self.DFSLG.setText(str(listgere[2]-1))
                        self.btn1.clicked.connect(lambda:self.afiche(listgere,pos))
                        return None
                case "BFS":
                        listgere=[]
                        listgere=file3.recherchBFS(file3.s0, file3.goal)
                        self.btn1.setEnabled(True)
                        self.btn1.clicked.connect(lambda:self.afiche(listgere,pos))
                        return None
                case "A*":
                        listgere=[]
                        listgere=file3.aetoile(file3.s0, file3.goal)
                        self.btn1.setEnabled(True)
                        self.btn1.clicked.connect(lambda:self.afiche(listgere,pos))
                        return None
               
    def clearr(self):
        c00,c01,c02,c10,c11,c12,c20,c21,c22=(1,2,3,8,6,"",7,5,4)
        self.col00.setText(str(c00))
        self.col01.setText(str(c01))
        self.col02.setText(str(c02))
        self.col10.setText(str(c10))
        self.col11.setText(str(c11))
        self.col12.setText(str(c12))
        self.col20.setText(str(c20))
        self.col21.setText(str(c21))
        self.col22.setText(str(c22))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.col00.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">1</span></p></body></html>"))
        self.col01.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">2</span></p></body></html>"))
        self.col02.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">3</span></p></body></html>"))
        self.col10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">4</span></p></body></html>"))
        self.col11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">6</span></p></body></html>"))
        self.col20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">7</span></p></body></html>"))
        self.col21.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">8</span></p></body></html>"))
        self.col22.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">5</span></p></body></html>"))
        self.btn2.setText(_translate("MainWindow", "start"))
        self.btn1.setText(_translate("MainWindow", "next"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">DFS</span></p></body></html>"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">BFS</span></p></body></html>"))
        self.textEdit_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">A*</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">DFSL</span></p></body></html>"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">nombre generated</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">nombre closed</span></p></body></html>"))
        self.DFSG.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">7</span></p></body></html>"))
        self.DFSC.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3</span></p></body></html>"))
        self.BFSG.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">18</span></p></body></html>"))
        self.BFSC.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">9</span></p></body></html>"))
        self.AG.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">12</span></p></body></html>"))
        self.AC.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "DFS"))
        self.comboBox.setItemText(1, _translate("MainWindow", "DFSL"))
        self.comboBox.setItemText(2, _translate("MainWindow", "BFS"))
        self.comboBox.setItemText(3, _translate("MainWindow", "A*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
